[package]
name        = "glium-screenshot"
version     = "0.0.0"
authors     = ["Casey Rodarmor <casey@rodarmor.com>"]
license     = "WTFPL"
description = "slow syncronous screenshot"

[dependencies]
# glium = "^0.15.0"

glium = { git = "https://github.com/tomaka/glium" }
image = "^0.10.3"
